### PR TITLE
Change package version to dev

### PR DESCRIPTION
**Pull request by fingolfin**
This way the version form git gets priority over the one bundled with GAP...

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
In which scenarios this is useful? In tests with Docker container for GAP, the clone of the repo is installed in user root, so it should have a priority (since the version in the GAP root is the same or older), isn't it?

I would find it very inconvenient if I need to add/remove `dev` from the version back and forth after each release.

**Comment by olexandr-konovalov** [comment]
@fingolfin could you please answer my question from the comment above?

**Comment by fingolfin** [comment]
@alex-konovalov This is useful whenever one wants to test the development version of a package while also having the standard set of packages installed (this scenarios seems pretty standard to me): If the latest released version is identical to the version in the package repository, then one has to be very careful to load the correct version of the package. It's very easy to end up loading the wrong one and then spending lots of time trying to debug an issue until one realizes that the wrong package (with identical version!) was loaded.

I don't see why this is "very inconvenient": You *have* to edit the version for each release anyway. So the only extra step is to manually add the "dev" version with a single commit; and in this case, hey, I did the work for you, so it's even just a single button press to do it, no? 

And I don't do this all the time for all my packages either; but if a package has major changes since the last release, and/or there is a lot of time between releases, I think it's very much advisable to add `dev` to the version.

**Comment by olexandr-konovalov** [comment]
@fingolfin thanks for the explanation. We are not then going to do this now, as we will likely release a new version shortly towards GAP 4.11. Then, in my local setup I don't have a problems with loading the right version - @vendramin do you have any? If you do not have any problems either, then I see a little merit in doing this, especially if we are not going to apply this consistently for each release.

**Comment by fingolfin** [comment]
Well, it would be helpful *for me*. And I think you already spent more time and effort debating this with me than it would have taken you to just merge it :-). And at zero cost, as I already explained, as you would need to edit the version for a release *regardless* of whether this PR is merged or not.

As it is, I'll stop arguing this, or on any of the other PRs. To be frank, trying to deal with issues in this package seems to be more of a hassle than it is worth it for me.

**Comment by olexandr-konovalov** [comment]
Well, I only wrote 9 lines so far ;-) Sorry I am still not convinced that "I need to edit the version for a release regardless of whether this PR is merged or not" - yes, I will edit it for next release, but then I should make another commit to add `dev` again, if I want to be consistent, isn't it?

Anyhow, I should better spend time on reviewing your other PRs (thanks for them).

**Pull request closed without merging**
