### PR TITLE
CI: test with GAP 4.13; test with mininimal set of packages loaded

### PR DESCRIPTION
**Pull request by fingolfin**
Unfortunately I expect that this will fail -- because it already
is failing on the PackageDistro tests. But we will see.

### CODE REVIEW

**Comment by fingolfin** [comment]
@vendramin just to double check: you saw that all tests fail with this merged?

**Comment by olexandr-konovalov** [comment]
@fingolfin ah, I see - so that's why yesterday tests were passing here, but not in PackageDistro. I think now, since it's merged, we are in sync, and can work on improving the tests in this repository.

**Comment by olexandr-konovalov** [comment]
@vendramin this is what @fingolfin refers to: https://github.com/gap-system/PackageDistro/pull/932

**Comment by vendramin** [comment]
I don’t quite understand why new problems appear every time. Is this easy to fix?

**Comment by olexandr-konovalov** [comment]
The testing of the package distro became more thorough, since it tests now also if the package runs with only required packages, omitting suggested ones. Now @fingolfin updated testing setup in this repository, so we should be able to run the same testing steps from now on. From https://github.com/gap-packages/YangBaxter/actions/runs/8410957154/job/23029997126#step:6:323 it looks like there is nothing serious, just some outputs are in different order, so it should be easy to fix, and that will help to make tests more robust in case of future randomness fluctuations.

**Comment by fingolfin** [comment]
To be clear, the PackageDistro always performed these tests. This PR just makes sure you run the same tests here, to make sure issues like these (which seem to be recent?) are discovered by you guys earlier

**Comment by fingolfin** [comment]
The failures seem to (mostly?) come from https://github.com/gap-packages/YangBaxter/commit/069c0d20bb1910ccf90f9df844e100be5d1a781a

**Pull request merged**
