### PR TITLE
Fix duplicate if condition.

### PR DESCRIPTION
**Pull request by ilafly**
Hi Leandro,

This commit fixes IsLeftIdeal by removing a duplicate if condition
that has been introduced in fc5f0025.

Ilaria Colazzo

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Thank you @ilafly! @vendramin do you think this is right, or something else was meant to be checked in https://github.com/gap-packages/YangBaxter/commit/fc5f002548be19611ade291187e2f0e330eafc5f ?

**Comment by olexandr-konovalov** [comment]
@vendramin ping?

**Review by fingolfin — APPROVED** [review]
This is obviously correct, but @vendramin should be the one to merge this.

**Comment by olexandr-konovalov** [comment]
@vendramin this pull request is waiting for your review (see GitHub help at https://help.github.com/en/articles/about-pull-request-reviews), or at least a comment here confirming that you have seen this and are happy with the suggested change. I am reluctant to make changes in the code without you seeing them, as this will lead to you not being informed about the chages.

**Comment by olexandr-konovalov** [comment]
Thanks @vendramin for merging this!

**Comment by fingolfin** [comment]
@vendramin yeah, thanks! but please note that there are still 8 more pull requests on this repository, and another three at https://github.com/gap-packages/rig/pulls

**Pull request merged**
