### PR TITLE
Resolve test issues

### PR DESCRIPTION
**Pull request by fingolfin**
... at least I hope it does. (Please don't merge this until it really makes all CI tests pass)

### CODE REVIEW

**Comment by fingolfin** [comment]
Yay, all green. @vendramin @olexandr-konovalov perhaps you can merge and then make a new release? If you do it tomorrow (Tuesday) you might even get it into GAP 4.13.1.

**Comment by fingolfin** [comment]
@vendramin @olexandr-konovalov would either of you either make a new release, or allow me to make one?

**Comment by vendramin** [comment]
Please make one. I cannot do it now. And thank you!On 15 Jun 2024, at 01:30, Max Horn ***@***.***> wrote:﻿
@vendramin @olexandr-konovalov would either of you either make a new release, or allow me to make one?

**Comment by olexandr-konovalov** [comment]
@fingolfin please make one! thanks!

**Pull request merged**
