### PR TITLE
Fix example for Fix()

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Review by vendramin — APPROVED** [review]

**Comment by fingolfin** [comment]
@vendramin you fixed the CI regression, but not properly: only the test generated from the example was fixed, not the example itself...

**Comment by fingolfin** [comment]
Let's see if the CI tests pass

**Comment by fingolfin** [comment]
OK the one against `master` will (still) fail, but that should be fixed by PR #81 (which I just rebased)

**Comment by fingolfin** [comment]
@vendramin merge the two PRs?

**Comment by fingolfin** [comment]
@vendramin thanks for merging. Can we please also have a new release of the package? As I said before, I'd be happy to make it (takes me at most 2 minutes of work), but I don't want to do this behind your back...

**Comment by vendramin** [comment]
Yes, please, make a new release. Thanks!

**Comment by olexandr-konovalov** [comment]
@fingolfin yes, if you could publish it, please go ahead, it would be helpful.

**Pull request merged**
